### ISSUE TITLE
.NCLR view size is increasing

### ISSUE THREAD

**Issue by myoaon01** [Garhoogin/NitroPaint#16] opened 2024-07-06 09:10 UTC
![oCam_240706_001-ezgif com-crop](https://github.com/Garhoogin/NitroPaint/assets/123155901/22d85c81-5db1-427e-a164-6dd14ee9656a)

As you can see, every time I insert a .NCLR file, the view size of the palette is increasing in NitroPaint 2.8.6.0. Because of this phenomenon, it is sometimes difficult to view windows because of the size of the palette every time a .NCLR file is imported.

I wonder if you can fix this part.ㅠ.ㅠ

**Comment by Garhoogin** [comment] 2024-07-07 21:02
Hi,

sorry you've experienced this issue. It's related to DPI scaling and only affects the palette editor. I'm away for the week so won't be able to do much about this now, but the issue is fixed as of a recent commit, though I haven't published a build yet since. If you're comfortable building from source, you would be able to see that fix incorporated, or if you're fine with waiting then in about a week I can publish a build with that fix implemented. Alternatively, to prevent it from happening, you may be able to override DPI settings for the application until an updated build is published.

Thanks for your understanding!

**Closed** 2024-07-08 06:07 UTC
