### ISSUE TITLE
Opening multiple files at once

### ISSUE THREAD

**Issue by opiter09** [Garhoogin/NitroPaint#19] opened 2024-11-24 23:27 UTC
I used to be able to open multiple files at once from command-line etc. by passing them all as arguments, so **NitroPaint.exe file1 file2**. Sometime after 2.9.0.0, this stopped working--it creates processes I can see in Task Manager, but nothing actually appears. Passing one file works fine, but I want to be able to pass multiple together so they are in the same window and "see" each other (passing in one file multiple times puts them all in different windows).

**Comment by Garhoogin** [comment] 2024-11-24 23:37
Hmm, I don't seem to be able to replicate this on my end, I've just tested it and was able to open two files by putting them together on the command line. I'm not sure why they wouldn't be opening correctly on your end since it seems you're doing the same. What was the last version it worked for you on, and which version were you using that it didn't?

Also, in the View menu you can enable "Single Instance," which makes it so that when you open files separately they'll open in the same window.

**Comment by opiter09** [comment] 2024-11-25 00:40
Okay, it seems I have misidentified the issue. The actual issue is that it will not let me run NSCR’s from the command line (nor can I double click them, but I can open them from a NitroPaint open menu). This is an issue with 2.9.2.0. I was not having issues with 2.9.0.0.

**Comment by opiter09** [comment] 2024-11-25 00:49
but here's the NSCR and its NCLR and NCGR to be safe: https://drive.google.com/file/d/1FaLyqw959zub3ozC0C1hP5F1hDjDPhAx/view?usp=drive_link

**Comment by Garhoogin** [comment] 2024-11-25 01:01
Odd, tried it just now with these files and it seemed to be working fine. I ran from the command line with all three file paths and it opened all 3 files correctly on my end. You're saying the issue is that the NSCR just isn't opening up? Does this happen for any other files?

**Comment by opiter09** [comment] 2024-11-25 01:13
No, the issue is that if an NSCR is included nothing opens at all.

**Comment by opiter09** [comment] 2024-11-25 01:13
But only opening the other two works fine for me.

**Comment by opiter09** [comment] 2024-11-25 01:29
And this issue happens with some files I tried from LEGO Battles as well.

**Comment by opiter09** [comment] 2024-11-25 01:33
okay! turning "DPI Aware" off fixed this

**Comment by Garhoogin** [comment] 2024-11-25 01:35
Hmm, that's a bizarre behavior. I'll have to look into that.

**Comment by opiter09** [comment] 2024-11-25 01:36
Is there anything you need to know about my computer? the resolution is 1920 x 1080, but I wouldn't know how to find my DPI

**Comment by Garhoogin** [comment] 2024-11-25 01:39
It couldn't hurt to know, but I don't think it's probably related to your specific DPI. If you go to your display settings there should be a UI scalar somewhere, maybe 125% or 150% perhaps. I won't be able to look into this today, but might be able to some time this week.

**Comment by opiter09** [comment] 2024-11-25 01:40
My scale is 125%. And thank you for looking into this, take all the time you need.

**Comment by Garhoogin** [comment] 2024-12-08 03:15
I was able to replicate this issue on my end using a 125% display scale factor and enabling DPI awareness. It looks as though the issue is stemming from scaling code in the NSCR viewer, which gets the program stuck. Then running a new instance of the program will see that the other exists and kill itself (when single-instance is enabled). Will look into a fix for this.

**Comment by opiter09** [comment] 2024-12-08 03:44
Wonderful, I’m glad you can replicate it, and thanks for looking into this.

**Closed** 2024-12-08 04:14 UTC
